name:                hasky-chess
version:             0.1.0.0
github:              "psq-cin/hasky-chess"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- pieces/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psq-cin/hasky-chess#readme>

dependencies:
- base >= 4.7 && < 5
- gloss >= 1.12.0.0
- gloss-juicy >= 0.2.2
- gloss-game >= 0.3.0.0
- containers
- stm

library:
  source-dirs: src

executables:
  hasky-chess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasky-chess

tests:
  hasky-chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasky-chess
